# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Admin\Desktop\gitlab\time_stop_machine\project\ui\newWindow_animated.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 40))
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toogle = QtWidgets.QFrame(self.top_bar)
        self.frame_toogle.setMaximumSize(QtCore.QSize(50, 40))
        self.frame_toogle.setStyleSheet("QFrame{\n"
"    background-color: #232323;\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"                                         \n"
"    background-color: #232323;\n"
"    border-style: solid;\n"
"    border-width:0px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  14px;\n"
"    padding: 0px;\n"
"    color:  #ff5533;\n"
"}\n"
"QPushButton:hover {\n"
"    background:  #2d2d2d;\n"
"    color:#262a2f;\n"
"} \n"
"QPushButton:pressed {                              \n"
"   background: #232323;\n"
"   border-style: solid; \n"
"   color:#ff5533;\n"
"}")
        self.frame_toogle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toogle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toogle.setObjectName("frame_toogle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toogle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_toogle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle.sizePolicy().hasHeightForWidth())
        self.btn_toggle.setSizePolicy(sizePolicy)
        self.btn_toggle.setStyleSheet("background-image: url(:/res_files/menu.png);\n"
"background-repeat:none;\n"
"background-position: center ;\n"
"")
        self.btn_toggle.setText("")
        self.btn_toggle.setIconSize(QtCore.QSize(32, 32))
        self.btn_toggle.setObjectName("btn_toggle")
        self.verticalLayout_2.addWidget(self.btn_toggle)
        self.horizontalLayout.addWidget(self.frame_toogle)
        self.frame_top = QtWidgets.QFrame(self.top_bar)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(50, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setStyleSheet("QFrame{\n"
"background-color: rgb(45, 45, 45);\n"
"\n"
"}\n"
"QPushButton {\n"
"    background-color: rgb(85, 255, 255);\n"
"                                         \n"
"    background-color: #232323;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  14px;\n"
"    padding: 10px 0px;\n"
"    color:  #ff5533;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background:  #2d2d2d;\n"
"    color: #ff5533;\n"
"} \n"
"QPushButton:pressed {                              \n"
"   background:#232323;\n"
"   border-style: solid; \n"
"   color:#ff5533;\n"
"}")
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_cur_mon = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_cur_mon.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_cur_mon.setStyleSheet("background-image: url(:/res_files/icon_curr.png);\n"
"background-repeat:none;\n"
"padding-left: 30px;\n"
"background-position: center left;\n"
"")
        self.btn_cur_mon.setIconSize(QtCore.QSize(16, 16))
        self.btn_cur_mon.setObjectName("btn_cur_mon")
        self.verticalLayout_4.addWidget(self.btn_cur_mon)
        self.btn_prev_mon = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_prev_mon.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_prev_mon.setStyleSheet("background-image: url(:/res_files/prev_mon.png);\n"
"background-repeat:none;\n"
"padding-left: 30px;\n"
"background-position: center left;\n"
"")
        self.btn_prev_mon.setObjectName("btn_prev_mon")
        self.verticalLayout_4.addWidget(self.btn_prev_mon)
        self.btn_select_date = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_select_date.setMinimumSize(QtCore.QSize(150, 40))
        self.btn_select_date.setStyleSheet("background-image: url(:/res_files/select.png);\n"
"background-repeat:none;\n"
"padding-left: 30px;\n"
"background-position: center left;\n"
"")
        self.btn_select_date.setObjectName("btn_select_date")
        self.verticalLayout_4.addWidget(self.btn_select_date)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Pages_Widjet = QtWidgets.QStackedWidget(self.frame_pages)
        self.Pages_Widjet.setMinimumSize(QtCore.QSize(0, 40))
        self.Pages_Widjet.setObjectName("Pages_Widjet")
        self.selected_data_page = QtWidgets.QWidget()
        self.selected_data_page.setObjectName("selected_data_page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.selected_data_page)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.options_frame_selected = QtWidgets.QFrame(self.selected_data_page)
        self.options_frame_selected.setMinimumSize(QtCore.QSize(0, 40))
        self.options_frame_selected.setMaximumSize(QtCore.QSize(16777215, 40))
        self.options_frame_selected.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.options_frame_selected.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.options_frame_selected.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options_frame_selected.setObjectName("options_frame_selected")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.options_frame_selected)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame = QtWidgets.QFrame(self.options_frame_selected)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.date_in = QtWidgets.QDateEdit(self.frame)
        self.date_in.setMinimumSize(QtCore.QSize(99, 25))
        self.date_in.setStyleSheet("QDateEdit {                                  \n"
"    background-color: #262a2f; \n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  16px;\n"
"    min-width: 5em;\n"
"    padding: 0px;\n"
"    color: #ffffff; \n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.date_in.setWrapping(False)
        self.date_in.setFrame(True)
        self.date_in.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.date_in.setReadOnly(False)
        self.date_in.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.date_in.setAccelerated(False)
        self.date_in.setProperty("showGroupSeparator", True)
        self.date_in.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 9, 14), QtCore.QTime(0, 0, 0)))
        self.date_in.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.date_in.setMaximumTime(QtCore.QTime(0, 0, 0))
        self.date_in.setCalendarPopup(True)
        self.date_in.setTimeSpec(QtCore.Qt.TimeZone)
        self.date_in.setObjectName("date_in")
        self.horizontalLayout_4.addWidget(self.date_in)
        self.date_out = QtWidgets.QDateEdit(self.frame)
        self.date_out.setMinimumSize(QtCore.QSize(99, 25))
        self.date_out.setToolTipDuration(-1)
        self.date_out.setStyleSheet("QDateEdit {\n"
"                                         \n"
"    background-color: #262a2f; \n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  16px;\n"
"    min-width: 5em;\n"
"    padding: 0px;\n"
"    color: #ffffff; \n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.date_out.setWrapping(False)
        self.date_out.setFrame(True)
        self.date_out.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.date_out.setReadOnly(False)
        self.date_out.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.date_out.setAccelerated(False)
        self.date_out.setProperty("showGroupSeparator", True)
        self.date_out.setDateTime(QtCore.QDateTime(QtCore.QDate(2021, 9, 15), QtCore.QTime(0, 0, 0)))
        self.date_out.setMinimumDate(QtCore.QDate(2021, 1, 1))
        self.date_out.setMaximumTime(QtCore.QTime(0, 0, 0))
        self.date_out.setCalendarPopup(True)
        self.date_out.setDate(QtCore.QDate(2021, 9, 15))
        self.date_out.setObjectName("date_out")
        self.horizontalLayout_4.addWidget(self.date_out)
        self.horizontalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.selected_data_label = QtWidgets.QLabel(self.options_frame_selected)
        self.selected_data_label.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.selected_data_label.setFont(font)
        self.selected_data_label.setStyleSheet("color: rgb(255, 255, 255);")
        self.selected_data_label.setObjectName("selected_data_label")
        self.horizontalLayout_3.addWidget(self.selected_data_label)
        self.frame_2 = QtWidgets.QFrame(self.options_frame_selected)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 29, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.update_selected_date = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_selected_date.sizePolicy().hasHeightForWidth())
        self.update_selected_date.setSizePolicy(sizePolicy)
        self.update_selected_date.setMinimumSize(QtCore.QSize(150, 25))
        self.update_selected_date.setMaximumSize(QtCore.QSize(150, 16777215))
        self.update_selected_date.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.update_selected_date.setAcceptDrops(False)
        self.update_selected_date.setToolTip("")
        self.update_selected_date.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.update_selected_date.setStyleSheet("QPushButton {\n"
"                                         \n"
"    background-color: #ff5533;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  16px;\n"
"    min-width: 5em;\n"
"    padding: 0px;\n"
"    color: #1e2027;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #262a2f; \n"
"    color:#ff5533;\n"
"} \n"
"QPushButton:pressed {                              \n"
"   background: #262a2f;\n"
"   border-style: solid; \n"
"   color:#ff5533;\n"
"}")
        self.update_selected_date.setAutoDefault(False)
        self.update_selected_date.setDefault(False)
        self.update_selected_date.setObjectName("update_selected_date")
        self.horizontalLayout_5.addWidget(self.update_selected_date)
        self.horizontalLayout_3.addWidget(self.frame_2, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_10.addWidget(self.options_frame_selected)
        self.plot_frame_selected = QtWidgets.QFrame(self.selected_data_page)
        self.plot_frame_selected.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plot_frame_selected.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_frame_selected.setObjectName("plot_frame_selected")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.plot_frame_selected)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.selected_plot_widget = QtWidgets.QWidget(self.plot_frame_selected)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selected_plot_widget.sizePolicy().hasHeightForWidth())
        self.selected_plot_widget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Modern")
        self.selected_plot_widget.setFont(font)
        self.selected_plot_widget.setStyleSheet("\n"
"background-color: rgb(45, 45, 45);")
        self.selected_plot_widget.setObjectName("selected_plot_widget")
        self.verticalLayout_11.addWidget(self.selected_plot_widget)
        self.verticalLayout_10.addWidget(self.plot_frame_selected)
        self.Pages_Widjet.addWidget(self.selected_data_page)
        self.curr_mon_page = QtWidgets.QWidget()
        self.curr_mon_page.setObjectName("curr_mon_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.curr_mon_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.options_frame_curr = QtWidgets.QFrame(self.curr_mon_page)
        self.options_frame_curr.setMinimumSize(QtCore.QSize(0, 40))
        self.options_frame_curr.setMaximumSize(QtCore.QSize(16777215, 40))
        self.options_frame_curr.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.options_frame_curr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.options_frame_curr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options_frame_curr.setObjectName("options_frame_curr")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.options_frame_curr)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_5 = QtWidgets.QFrame(self.options_frame_curr)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7.addWidget(self.frame_5)
        self.selected_data_label_3 = QtWidgets.QLabel(self.options_frame_curr)
        self.selected_data_label_3.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.selected_data_label_3.setFont(font)
        self.selected_data_label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.selected_data_label_3.setObjectName("selected_data_label_3")
        self.horizontalLayout_7.addWidget(self.selected_data_label_3)
        spacerItem1 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.frame_6 = QtWidgets.QFrame(self.options_frame_curr)
        self.frame_6.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_8.setContentsMargins(0, 0, 30, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.update_curr_mon = QtWidgets.QPushButton(self.frame_6)
        self.update_curr_mon.setMinimumSize(QtCore.QSize(150, 25))
        self.update_curr_mon.setMaximumSize(QtCore.QSize(150, 16777215))
        self.update_curr_mon.setStyleSheet("QPushButton {\n"
"                                         \n"
"    background-color: #ff5533;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  16px;\n"
"    min-width: 5em;\n"
"    padding: 0px;\n"
"    color: #1e2027;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #262a2f; \n"
"    color:#ff5533;\n"
"} \n"
"QPushButton:pressed {                              \n"
"   background: #262a2f;\n"
"   border-style: solid; \n"
"   color:#ff5533;\n"
"}")
        self.update_curr_mon.setObjectName("update_curr_mon")
        self.horizontalLayout_8.addWidget(self.update_curr_mon)
        self.horizontalLayout_7.addWidget(self.frame_6, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_6.addWidget(self.options_frame_curr)
        self.plot_frame_curr = QtWidgets.QFrame(self.curr_mon_page)
        self.plot_frame_curr.setStyleSheet("\n"
"background-color: rgb(45, 45, 45);")
        self.plot_frame_curr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plot_frame_curr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_frame_curr.setObjectName("plot_frame_curr")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.plot_frame_curr)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.curr_plot_widget = QtWidgets.QWidget(self.plot_frame_curr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curr_plot_widget.sizePolicy().hasHeightForWidth())
        self.curr_plot_widget.setSizePolicy(sizePolicy)
        self.curr_plot_widget.setStyleSheet("\n"
"background-color: rgb(45, 45, 45);")
        self.curr_plot_widget.setObjectName("curr_plot_widget")
        self.verticalLayout_9.addWidget(self.curr_plot_widget)
        self.verticalLayout_6.addWidget(self.plot_frame_curr)
        self.Pages_Widjet.addWidget(self.curr_mon_page)
        self.prev_mon_page = QtWidgets.QWidget()
        self.prev_mon_page.setObjectName("prev_mon_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.prev_mon_page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.options_frame_prev = QtWidgets.QFrame(self.prev_mon_page)
        self.options_frame_prev.setMinimumSize(QtCore.QSize(0, 40))
        self.options_frame_prev.setMaximumSize(QtCore.QSize(16777215, 40))
        self.options_frame_prev.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.options_frame_prev.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.options_frame_prev.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options_frame_prev.setObjectName("options_frame_prev")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.options_frame_prev)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.options_frame_prev)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6.addWidget(self.frame_3)
        self.selected_data_label_2 = QtWidgets.QLabel(self.options_frame_prev)
        self.selected_data_label_2.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(14)
        self.selected_data_label_2.setFont(font)
        self.selected_data_label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.selected_data_label_2.setObjectName("selected_data_label_2")
        self.horizontalLayout_6.addWidget(self.selected_data_label_2)
        spacerItem2 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.frame_4 = QtWidgets.QFrame(self.options_frame_prev)
        self.frame_4.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_12.setContentsMargins(0, 0, 30, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.update_prev_mon = QtWidgets.QPushButton(self.frame_4)
        self.update_prev_mon.setMinimumSize(QtCore.QSize(99, 25))
        self.update_prev_mon.setMaximumSize(QtCore.QSize(150, 16777215))
        self.update_prev_mon.setStyleSheet("QPushButton {\n"
"                                         \n"
"    background-color: #ff5533;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  16px;\n"
"    min-width: 5em;\n"
"    padding: 0px;\n"
"    color: #1e2027;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #262a2f; \n"
"    color:#ff5533;\n"
"} \n"
"QPushButton:pressed {                              \n"
"   background: #262a2f;\n"
"   border-style: solid; \n"
"   color:#ff5533;\n"
"}")
        self.update_prev_mon.setObjectName("update_prev_mon")
        self.verticalLayout_12.addWidget(self.update_prev_mon)
        self.horizontalLayout_6.addWidget(self.frame_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_7.addWidget(self.options_frame_prev)
        self.plot_frame_prev = QtWidgets.QFrame(self.prev_mon_page)
        self.plot_frame_prev.setStyleSheet("\n"
"background-color: rgb(45, 45, 45);")
        self.plot_frame_prev.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plot_frame_prev.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_frame_prev.setObjectName("plot_frame_prev")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.plot_frame_prev)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.prev_plot_widget = QtWidgets.QWidget(self.plot_frame_prev)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_plot_widget.sizePolicy().hasHeightForWidth())
        self.prev_plot_widget.setSizePolicy(sizePolicy)
        self.prev_plot_widget.setStyleSheet("\n"
"background-color: rgb(45, 45, 45);")
        self.prev_plot_widget.setObjectName("prev_plot_widget")
        self.verticalLayout_8.addWidget(self.prev_plot_widget)
        self.verticalLayout_7.addWidget(self.plot_frame_prev)
        self.Pages_Widjet.addWidget(self.prev_mon_page)
        self.verticalLayout_5.addWidget(self.Pages_Widjet)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages_Widjet.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_cur_mon.setText(_translate("MainWindow", "Текущий месяц"))
        self.btn_prev_mon.setText(_translate("MainWindow", "Прошлый месяц"))
        self.btn_select_date.setText(_translate("MainWindow", "Выбрать дату"))
        self.date_in.setToolTip(_translate("MainWindow", "Выберете начальную дату"))
        self.date_out.setToolTip(_translate("MainWindow", "Выберете конечную дату"))
        self.selected_data_label.setText(_translate("MainWindow", "Диаграммы по выбранной дате"))
        self.update_selected_date.setText(_translate("MainWindow", "Показать"))
        self.selected_data_label_3.setText(_translate("MainWindow", "Диаграммы по текущему месяцу"))
        self.update_curr_mon.setText(_translate("MainWindow", "Показать"))
        self.selected_data_label_2.setText(_translate("MainWindow", "Диаграммы по прошлому месяцу"))
        self.update_prev_mon.setText(_translate("MainWindow", "Показать"))

