# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_bar = QtWidgets.QFrame(self.centralwidget)
        self.top_bar.setMinimumSize(QtCore.QSize(0, 40))
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toogle = QtWidgets.QFrame(self.top_bar)
        self.frame_toogle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toogle.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_toogle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toogle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toogle.setObjectName("frame_toogle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toogle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_toggle = QtWidgets.QPushButton(self.frame_toogle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle.sizePolicy().hasHeightForWidth())
        self.btn_toggle.setSizePolicy(sizePolicy)
        self.btn_toggle.setStyleSheet("QPushButton {\n"
"                                         \n"
"    background-color: #262a2f;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  14px;\n"
"    padding: 0px;\n"
"    color:  #ff5533;\n"
"}\n"
"QPushButton:hover {\n"
"    background:  #ff5533;\n"
"    color:#262a2f;\n"
"} \n"
"QPushButton:pressed {                              \n"
"   background: #262a2f;\n"
"   border-style: solid; \n"
"   color:#ff5533;\n"
"}")
        self.btn_toggle.setObjectName("btn_toggle")
        self.verticalLayout_2.addWidget(self.btn_toggle)
        self.horizontalLayout.addWidget(self.frame_toogle)
        self.frame_top = QtWidgets.QFrame(self.top_bar)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.top_bar)
        self.content = QtWidgets.QFrame(self.centralwidget)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(150, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_cur_mon = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_cur_mon.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_cur_mon.setStyleSheet("QPushButton {\n"
"                                         \n"
"    background-color: #232323;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  14px;\n"
"    padding: 0px;\n"
"    color:  #ff5533;\n"
"}\n"
"QPushButton:hover {\n"
"    background:  #ff5533;\n"
"    color:#262a2f;\n"
"} \n"
"QPushButton:pressed {                              \n"
"   background: #262a2f;\n"
"   border-style: solid; \n"
"   color:#ff5533;\n"
"}")
        self.btn_cur_mon.setObjectName("btn_cur_mon")
        self.verticalLayout_4.addWidget(self.btn_cur_mon)
        self.btn_prev_mon = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_prev_mon.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_prev_mon.setStyleSheet("QPushButton {\n"
"                                         \n"
"    background-color: #232323;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  14px;\n"
"    padding: 0px;\n"
"    color:  #ff5533;\n"
"}\n"
"QPushButton:hover {\n"
"    background:  #ff5533;\n"
"    color:#262a2f;\n"
"} \n"
"QPushButton:pressed {                              \n"
"   background: #262a2f;\n"
"   border-style: solid; \n"
"   color:#ff5533;\n"
"}")
        self.btn_prev_mon.setObjectName("btn_prev_mon")
        self.verticalLayout_4.addWidget(self.btn_prev_mon)
        self.btn_select_date = QtWidgets.QPushButton(self.frame_top_menus)
        self.btn_select_date.setMinimumSize(QtCore.QSize(0, 40))
        self.btn_select_date.setStyleSheet("QPushButton {\n"
"                                         \n"
"    background-color:#232323;\n"
"    border-style: solid;\n"
"    border-width: 0px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  14px;\n"
"    padding: 0px;\n"
"    color:  #ff5533;\n"
"}\n"
"QPushButton:hover {\n"
"    background:  #ff5533;\n"
"    color:#262a2f;\n"
"} \n"
"QPushButton:pressed {                              \n"
"   background: #262a2f;\n"
"   border-style: solid; \n"
"   color:#ff5533;\n"
"}")
        self.btn_select_date.setObjectName("btn_select_date")
        self.verticalLayout_4.addWidget(self.btn_select_date)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Pages_Widjet = QtWidgets.QStackedWidget(self.frame_pages)
        self.Pages_Widjet.setMinimumSize(QtCore.QSize(0, 40))
        self.Pages_Widjet.setObjectName("Pages_Widjet")
        self.curr_mon_page = QtWidgets.QWidget()
        self.curr_mon_page.setObjectName("curr_mon_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.curr_mon_page)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.options_frame_curr = QtWidgets.QFrame(self.curr_mon_page)
        self.options_frame_curr.setMinimumSize(QtCore.QSize(0, 40))
        self.options_frame_curr.setMaximumSize(QtCore.QSize(16777215, 40))
        self.options_frame_curr.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.options_frame_curr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.options_frame_curr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options_frame_curr.setObjectName("options_frame_curr")
        self.update_curr_mon = QtWidgets.QPushButton(self.options_frame_curr)
        self.update_curr_mon.setGeometry(QtCore.QRect(630, 0, 131, 31))
        self.update_curr_mon.setStyleSheet("QPushButton {\n"
"                                         \n"
"    background-color: #ff5533;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  16px;\n"
"    min-width: 5em;\n"
"    padding: 0px;\n"
"    color: #1e2027;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #262a2f; \n"
"    color:#ff5533;\n"
"} \n"
"QPushButton:pressed {                              \n"
"   background: #262a2f;\n"
"   border-style: solid; \n"
"   color:#ff5533;\n"
"}")
        self.update_curr_mon.setObjectName("update_curr_mon")
        self.time_curr_mon = QtWidgets.QTextEdit(self.options_frame_curr)
        self.time_curr_mon.setGeometry(QtCore.QRect(10, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.time_curr_mon.setFont(font)
        self.time_curr_mon.setStyleSheet("QTextEdit {\n"
"                                         \n"
"    background-color: #262a2f; \n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  16px;\n"
"    min-width: 1em;\n"
"    padding: 0px;\n"
"    color: #ffffff;\n"
"}\n"
"QTextEdit:hover {\n"
"    background: #262a2f; \n"
"    color:#ffffff;\n"
"} ")
        self.time_curr_mon.setLineWrapColumnOrWidth(0)
        self.time_curr_mon.setObjectName("time_curr_mon")
        self.label = QtWidgets.QLabel(self.options_frame_curr)
        self.label.setGeometry(QtCore.QRect(290, 10, 131, 16))
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.options_frame_curr)
        self.plot_frame_curr = QtWidgets.QFrame(self.curr_mon_page)
        self.plot_frame_curr.setStyleSheet("\n"
"background-color: rgb(45, 45, 45);")
        self.plot_frame_curr.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plot_frame_curr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_frame_curr.setObjectName("plot_frame_curr")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.plot_frame_curr)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.curr_plot_widget = QtWidgets.QWidget(self.plot_frame_curr)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.curr_plot_widget.sizePolicy().hasHeightForWidth())
        self.curr_plot_widget.setSizePolicy(sizePolicy)
        self.curr_plot_widget.setStyleSheet("\n"
"background-color: rgb(45, 45, 45);")
        self.curr_plot_widget.setObjectName("curr_plot_widget")
        self.label_3 = QtWidgets.QLabel(self.curr_plot_widget)
        self.label_3.setGeometry(QtCore.QRect(370, 120, 131, 16))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.curr_plot_widget)
        self.verticalLayout_6.addWidget(self.plot_frame_curr)
        self.Pages_Widjet.addWidget(self.curr_mon_page)
        self.prev_mon_page = QtWidgets.QWidget()
        self.prev_mon_page.setObjectName("prev_mon_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.prev_mon_page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.options_frame_prev = QtWidgets.QFrame(self.prev_mon_page)
        self.options_frame_prev.setMinimumSize(QtCore.QSize(0, 40))
        self.options_frame_prev.setMaximumSize(QtCore.QSize(16777215, 40))
        self.options_frame_prev.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.options_frame_prev.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.options_frame_prev.setFrameShadow(QtWidgets.QFrame.Raised)
        self.options_frame_prev.setObjectName("options_frame_prev")
        self.update_prev_mon = QtWidgets.QPushButton(self.options_frame_prev)
        self.update_prev_mon.setGeometry(QtCore.QRect(630, 0, 131, 31))
        self.update_prev_mon.setStyleSheet("QPushButton {\n"
"                                         \n"
"    background-color: #ff5533;\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  16px;\n"
"    min-width: 5em;\n"
"    padding: 0px;\n"
"    color: #1e2027;\n"
"}\n"
"QPushButton:hover {\n"
"    background: #262a2f; \n"
"    color:#ff5533;\n"
"} \n"
"QPushButton:pressed {                              \n"
"   background: #262a2f;\n"
"   border-style: solid; \n"
"   color:#ff5533;\n"
"}")
        self.update_prev_mon.setObjectName("update_prev_mon")
        self.time_prev_mon = QtWidgets.QTextEdit(self.options_frame_prev)
        self.time_prev_mon.setGeometry(QtCore.QRect(10, 0, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.time_prev_mon.setFont(font)
        self.time_prev_mon.setStyleSheet("QTextEdit {\n"
"                                         \n"
"    background-color: #262a2f; \n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"    border-radius: 0px;\n"
"    border-color: #ff5533;\n"
"    font:  16px;\n"
"    min-width: 1em;\n"
"    padding: 0px;\n"
"    color: #ffffff;\n"
"}\n"
"QTextEdit:hover {\n"
"    background: #262a2f; \n"
"    color:#ffffff;\n"
"} ")
        self.time_prev_mon.setLineWrapColumnOrWidth(0)
        self.time_prev_mon.setObjectName("time_prev_mon")
        self.label_2 = QtWidgets.QLabel(self.options_frame_prev)
        self.label_2.setGeometry(QtCore.QRect(350, 10, 131, 16))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.options_frame_prev)
        self.plot_frame_prev = QtWidgets.QFrame(self.prev_mon_page)
        self.plot_frame_prev.setStyleSheet("\n"
"background-color: rgb(45, 45, 45);")
        self.plot_frame_prev.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.plot_frame_prev.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plot_frame_prev.setObjectName("plot_frame_prev")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.plot_frame_prev)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.prev_plot_widget = QtWidgets.QWidget(self.plot_frame_prev)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prev_plot_widget.sizePolicy().hasHeightForWidth())
        self.prev_plot_widget.setSizePolicy(sizePolicy)
        self.prev_plot_widget.setStyleSheet("\n"
"background-color: rgb(45, 45, 45);")
        self.prev_plot_widget.setObjectName("prev_plot_widget")
        self.verticalLayout_8.addWidget(self.prev_plot_widget)
        self.verticalLayout_7.addWidget(self.plot_frame_prev)
        self.Pages_Widjet.addWidget(self.prev_mon_page)
        self.verticalLayout_5.addWidget(self.Pages_Widjet)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Pages_Widjet.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_toggle.setText(_translate("MainWindow", "TOGGLE"))
        self.btn_cur_mon.setText(_translate("MainWindow", "Текущий месяц"))
        self.btn_prev_mon.setText(_translate("MainWindow", "Прошлый месяц"))
        self.btn_select_date.setText(_translate("MainWindow", "Выбрать дату"))
        self.update_curr_mon.setText(_translate("MainWindow", "Обновить"))
        self.time_curr_mon.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">300</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Текущий месяц"))
        self.label_3.setText(_translate("MainWindow", "Текущий месяц"))
        self.update_prev_mon.setText(_translate("MainWindow", "Обновить"))
        self.time_prev_mon.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16px;\">300</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "Прошлый месяц"))
